# Generated by Django 6.0.1 on 2026-02-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                (
                    "image1",
                    models.ImageField(blank=True, null=True, upload_to="characters/"),
                ),
                (
                    "image2",
                    models.ImageField(blank=True, null=True, upload_to="characters/"),
                ),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="characters/"),
                ),
                ("is_alive", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
