# Generated by Django 6.0.1 on 2026-02-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="image1",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="image2",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="character",
            name="image3",
            field=models.URLField(blank=True, null=True),
        ),
    ]
